### ISSUE TITLE
 UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443

### ISSUE THREAD

**Issue by noheton** [codetheweb/MMM-AnyList#5]
Unfortunately, the `MMM-Anylist` module is not working anymore.
Did a fresh install of my Magic Mirror today.
Seems like a decrepation issue within `got` library which is referenced by the `anylist ` module.

Steps to reproduce:
1. clone repository
2. cd MMM-Anylist
3. npm install
4. pm2 restart all

Output:
```
[2020-08-11 20:36:02.693] [ERROR]  (node:12815) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2020-08-11 20:36:02.706] [ERROR]  (node:12815) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2020-08-11 20:36:02.707] [ERROR]  (node:12815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-08-11 20:36:02.708] [ERROR]  (node:12815) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-08-11 20:36:02.708] [ERROR]  (node:12815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-08-11 20:36:02.709] [ERROR]  (node:12815) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
No output to mirror at all.

Node version `v10.22.0` running on Raspberry Pi 3 B+.

Let me know if I can test anything.

Best regards,
Florian

**Comment by codetheweb** [comment]
It shouldn't be trying to connect to port 443 on localhost, and if there's no service running there the error makes sense. Is there any kind of proxy configuration in your environment variables or on your machine? Are you able to try running this on a different machine to see if you get the same error?

**Comment by noheton** [comment]
yep - 443 caught my eye too. the mirror isn't even running on SSL.
No proxy as far as I know.

module config is also pretty standard:
```
    {
      module: 'MMM-AnyList',
      position: 'bottom_left',
      config: {
        email: ###redacted
        password: ###redacted
        list: 'Alexa Shopping List',
        // Optional, values listed are the defaults
        onlyShowUnchecked: true,
        maxItemsInList: 30,
        highlightAlternateRows: false,
        highlightColor: 'darkslategrey',
        fade: false,
        fadePoint: 0.5,
        animationSpeed: 2000,
      }
    },
```
just ran the module all by itself - no change.
```
[2020-08-11 21:05:37.590] [ERROR]  (node:14830) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2020-08-11 21:05:37.592] [ERROR]  (node:14830) UnhandledPromiseRejectionWarning: GotError: connect ECONNREFUSED 127.0.0.1:443
    at onError (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:140:29)
    at handleRequest (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:173:17)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)
[2020-08-11 21:05:37.594] [ERROR]  (node:14830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-08-11 21:05:37.595] [ERROR]  (node:14830) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[2020-08-11 21:05:37.596] [ERROR]  (node:14830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2020-08-11 21:05:37.597] [ERROR]  (node:14830) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
Unfortunately, I don't have a second machine to test on.

**Comment by noheton** [comment]
ahh ... my bad, when I run it by itself it works.

https://github.com/PalatinCoder/MMM-GoogleBirthdaysProvider
seems to cause some issues.
```
module: "MMM-GoogleBirthdaysProvider",
      config: {}
},
```
still have to figure this one out though...

**Comment by codetheweb** [comment]
Interesting.

Good luck, hope you figure it out.

**Comment by eirikaho** [comment]
> ahh ... my bad, when I run it by itself it works.
> 
> https://github.com/PalatinCoder/MMM-GoogleBirthdaysProvider
> seems to cause some issues.
> 
> ```
> module: "MMM-GoogleBirthdaysProvider",
>       config: {}
> },
> ```
> 
> still have to figure this one out though...

@codetheweb Did you manage to figure this out? I'm experiencing the same behavior when https://github.com/slametps/MMM-NetworkConnection is present. (`RequestError: connect ECONNREFUSED 127.0.0.1:443`)

config
```
	modules: [
			{
			module: 'MMM-NetworkConnection',
			position: 'bottom_bar',
			config: { ... }
		},
		{
			module: 'MMM-AnyList',
			position: 'top_left',
			config: { ... }
		}
	]
```
