### ISSUE TITLE
Improvement : Whish I could ad a second list

### ISSUE THREAD

**Issue by MoRobo** [codetheweb/MMM-AnyList#7]
It would be nice to have more than one list on display.
May it be possible?

**Comment by codetheweb** [comment]
I believe you can already do this by adding this module to your config more than once in different locations.

**Comment by MoRobo** [comment]
Does not work: 
[2020-09-09 15:20:07.672] [ERROR]  (node:4535) UnhandledPromiseRejectionWarning: GotError: Invalid value "undefined" for header "x-anyleaf-signed-user-id"
    at get (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
    at ClientRequest.setHeader (_http_outgoing.js:458:3)
    at new ClientRequest (_http_client.js:221:14)
    at Object.request (https.js:309:10)
    at get (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:197:65)
    at async /home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:264:13
[2020-09-09 15:20:07.679] [ERROR]  (node:4535) UnhandledPromiseRejectionWarning: GotError: Invalid value "undefined" for header "x-anyleaf-signed-user-id"
    at get (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:200:27)
    at ClientRequest.setHeader (_http_outgoing.js:458:3)
    at new ClientRequest (_http_client.js:221:14)
    at Object.request (https.js:309:10)
    at get (/home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:197:65)
    at async /home/pi/MagicMirror/modules/MMM-AnyList/node_modules/anylist/node_modules/got/dist/source/request-as-event-emitter.js:264:13

it shows the same list twice, although i set another list in the second place.

**Comment by codetheweb** [comment]
Weird, I was able to reproduce this.
I'll look into it. 👍

**Comment by codetheweb** [comment]
It should be fixed now, please pull and try again.

**Comment by MoRobo** [comment]
Yeah!
It works perfect!

Thank you sooo much
Joe
